---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
   - name: Gather all registered virtual machines
     local_action:
       module: vmware_vm_facts
       hostname: 192.168.10.227
       username: root
       password: openstack
       validate_certs: no
     register: vmware
   - name: print
     debug: var=vmware
